### ISSUE TITLE
"jdeps -jdkinternals" throwing usage of JDK internal API

### ISSUE THREAD

**Issue by ilapavuluri** [ehcache/ehcache2#46]
Hi Team,

As part of Java17 upgrade when I ran "jdeps -jdkinternals ehcache-core.jar" I am getting below error:

 net.sf.ehcache.pool.sizeof.UnsafeSizeOf (ehcache-core.jar)
      -> sun.misc.Unsafe                                    JDK internal API (rt.jar)

It is complaining about usage of internal API's.

Please do the needful.

Thanks
Ashok.

**Comment by jhouserizer** [comment]
Nothing can be done about this.   The SizeOf feature was built with 3 different techniques for determining Object size ... three techniques because each was known to use internals, and so the hope was that if the ability to use one technique "went away" , there would still be the two other means of doing it.  Unfortunately, Java 17 removes all 3 mechanisms all at once.

You should move to Ehcache 3.x.

Alernatively, keep using Ehcache 2.x but do not use byte-sized capacity of heap tiers on caches (use only count-based capacity), and Ehcache 2 will then continue to work.
